In [1]:
import pandas as pd
from IPython.display import display, HTML

def section(title):
    display(HTML(f"""
    <div style="margin:15px 0;">
        <hr style="border:1px solid #aaa;">
        <h2 style="color:#333;">{title}</h2>
        <hr style="border:1px solid #aaa;">
    </div>
    """))

# kvmem={0.3,0.9} offload=20, MNS=30
# OK:
# 1. NONE foi melhor. FCFS equivalente ao RR, como esperado. NONE será ignorado
# 2. Usando kvmem 0.9, todos iguais, já q não precisava de preempção.
#    Em sharegpt RR foi melhor. Significativo? Mais repetições.
# 3. Usando kvmem 0.3, existe preempção. RR era para ser melhor ou pior???

data = [{'date': '20260416-150431', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 116.02795221609995, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 0.25855838551839255, 'request_goodput': None, 'output_throughput': 491.26093248494584, 'total_token_throughput': 492.5537244125378, 'mean_ttft_ms': 33.13800563725332, 'median_ttft_ms': 33.45606243237853, 'std_ttft_ms': 3.216340554912415, 'p50_ttft_ms': 33.45606243237853, 'p75_ttft_ms': 35.3994615143165, 'p90_ttft_ms': 37.147540133446455, 'p99_ttft_ms': 38.21850716136396, 'mean_tpot_ms': 37.45099282328171, 'median_tpot_ms': 38.29905056316658, 'std_tpot_ms': 14.946615590765242, 'p50_tpot_ms': 38.29905056316658, 'p75_tpot_ms': 50.47639816329511, 'p90_tpot_ms': 57.22240014582884, 'p99_tpot_ms': 60.38951042831128, 'mean_itl_ms': 37.4509929149345, 'median_itl_ms': 15.734018292278051, 'std_itl_ms': 1059.23389233441, 'p50_itl_ms': 15.734018292278051, 'p75_itl_ms': 16.189926769584417, 'p90_itl_ms': 16.42261305823922, 'p99_itl_ms': 16.945969308726486, 'mean_e2el_ms': 71152.57337704922, 'median_e2el_ms': 72762.17208290473, 'std_e2el_ms': 28382.080023256945, 'p50_e2el_ms': 72762.17208290473, 'p75_e2el_ms': 95885.71923249401, 'p90_e2el_ms': 108692.10717454553, 'p99_e2el_ms': 114709.5623237826, 'scheduler': 'fcfs.Scheduler', 'offload': '4', 'kvmem': '0.3', 'test_case': 'throughput'}, {'date': '20260416-150500', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 12.076977284159511, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6394, 'request_throughput': 2.4840652834007404, 'request_goodput': None, 'output_throughput': 529.4371140688111, 'total_token_throughput': 1069.5557088562455, 'mean_ttft_ms': 151.12454138385752, 'median_ttft_ms': 155.44906305149198, 'std_ttft_ms': 71.38814052844116, 'p50_ttft_ms': 155.44906305149198, 'p75_ttft_ms': 195.53535024169832, 'p90_ttft_ms': 242.91398827917874, 'p99_ttft_ms': 246.1207087477669, 'mean_tpot_ms': 18.735331605477754, 'median_tpot_ms': 16.5183798554514, 'std_tpot_ms': 6.45369424378, 'p50_tpot_ms': 16.5183798554514, 'p75_tpot_ms': 17.9573855518053, 'p90_tpot_ms': 20.19591163208877, 'p99_tpot_ms': 42.01646281639114, 'mean_itl_ms': 16.36743328360212, 'median_itl_ms': 15.982685144990683, 'std_itl_ms': 7.009501801360159, 'p50_itl_ms': 15.982685144990683, 'p75_itl_ms': 16.312625957652926, 'p90_itl_ms': 16.624844586476684, 'p99_itl_ms': 17.10064106155187, 'mean_e2el_ms': 3623.2026032948243, 'median_e2el_ms': 2491.0967983305454, 'std_e2el_ms': 3275.276759929144, 'p50_e2el_ms': 2491.0967983305454, 'p75_e2el_ms': 5420.817855861969, 'p90_e2el_ms': 7616.739062406125, 'p99_e2el_ms': 11983.999221269041, 'scheduler': 'fcfs.Scheduler', 'offload': '4', 'kvmem': '0.3', 'test_case': 'share'}, {'date': '20260416-151253', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 136.52350254217163, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 0.21974238458124165, 'request_goodput': None, 'output_throughput': 417.51053070435916, 'total_token_throughput': 418.60924262726536, 'mean_ttft_ms': 33.886116944874324, 'median_ttft_ms': 33.51653995923698, 'std_ttft_ms': 3.3140449416301614, 'p50_ttft_ms': 33.51653995923698, 'p75_ttft_ms': 36.469466518610716, 'p90_ttft_ms': 37.31882502324879, 'p99_ttft_ms': 40.95892946701497, 'mean_tpot_ms': 67.04974334007916, 'median_tpot_ms': 68.07198390752575, 'std_tpot_ms': 3.699687539487914, 'p50_tpot_ms': 68.07198390752575, 'p75_tpot_ms': 69.83093499905355, 'p90_tpot_ms': 71.64873233086588, 'p99_tpot_ms': 71.82279947229033, 'mean_itl_ms': 67.04974343102084, 'median_itl_ms': 15.990924090147018, 'std_itl_ms': 852.3330906222286, 'p50_itl_ms': 15.990924090147018, 'p75_itl_ms': 16.35187608189881, 'p90_itl_ms': 16.6580512188375, 'p99_itl_ms': 36.04591826442628, 'mean_e2el_ms': 127361.34871975519, 'median_e2el_ms': 129301.71978008002, 'std_e2el_ms': 7025.921923380649, 'p50_e2el_ms': 129301.71978008002, 'p75_e2el_ms': 132644.9542044429, 'p90_e2el_ms': 136098.00675367005, 'p99_e2el_ms': 136425.67365093622, 'scheduler': 'rr.Scheduler', 'offload': '4', 'kvmem': '0.3', 'test_case': 'throughput'}, {'date': '20260416-151659', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 125.74851162033156, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 0.2385714122054823, 'request_goodput': None, 'output_throughput': 453.28568319041636, 'total_token_throughput': 454.47854025144375, 'mean_ttft_ms': 32.47252187381188, 'median_ttft_ms': 32.46314078569412, 'std_ttft_ms': 3.4433164014272726, 'p50_ttft_ms': 32.46314078569412, 'p75_ttft_ms': 34.78532622102648, 'p90_ttft_ms': 37.01229952275753, 'p99_ttft_ms': 38.913558279164135, 'mean_tpot_ms': 61.274805482021165, 'median_tpot_ms': 62.44728404988366, 'std_tpot_ms': 3.395357035069557, 'p50_tpot_ms': 62.44728404988366, 'p75_tpot_ms': 63.96687706767397, 'p90_tpot_ms': 64.90317397462051, 'p99_tpot_ms': 65.88845438145646, 'mean_itl_ms': 61.2748055809977, 'median_itl_ms': 16.07633731327951, 'std_itl_ms': 765.712873165389, 'p50_itl_ms': 16.07633731327951, 'p75_itl_ms': 16.480388585478067, 'p90_itl_ms': 16.803170554339886, 'p99_itl_ms': 28.540096092037853, 'mean_e2el_ms': 116393.32813223203, 'median_e2el_ms': 118622.54943186417, 'std_e2el_ms': 6446.107158506144, 'p50_e2el_ms': 118622.54943186417, 'p75_e2el_ms': 121502.69520841539, 'p90_e2el_ms': 123281.00089901127, 'p99_e2el_ms': 125149.75260810927, 'scheduler': 'rr.Scheduler', 'offload': '20', 'kvmem': '0.3', 'test_case': 'throughput'}, {'date': '20260416-151727', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 10.604821955319494, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6394, 'request_throughput': 2.8289018077245203, 'request_goodput': None, 'output_throughput': 602.9332719530195, 'total_token_throughput': 1218.0308216792544, 'mean_ttft_ms': 150.47065016503137, 'median_ttft_ms': 132.68171157687902, 'std_ttft_ms': 76.35798167733736, 'p50_ttft_ms': 132.68171157687902, 'p75_ttft_ms': 206.53089589904994, 'p90_ttft_ms': 249.7716630809009, 'p99_ttft_ms': 252.7100250963122, 'mean_tpot_ms': 19.125391539144985, 'median_tpot_ms': 16.49395608632215, 'std_tpot_ms': 8.09285291090323, 'p50_tpot_ms': 16.49395608632215, 'p75_tpot_ms': 17.82462855307273, 'p90_tpot_ms': 21.745076478162602, 'p99_tpot_ms': 48.85133675113318, 'mean_itl_ms': 15.802586333879452, 'median_itl_ms': 15.980939380824566, 'std_itl_ms': 7.225219064831046, 'p50_itl_ms': 15.980939380824566, 'p75_itl_ms': 16.33605535607785, 'p90_itl_ms': 16.593223018571734, 'p99_itl_ms': 17.012335737235844, 'mean_e2el_ms': 3502.725855136911, 'median_e2el_ms': 2494.1404692362994, 'std_e2el_ms': 2992.90517071345, 'p50_e2el_ms': 2494.1404692362994, 'p75_e2el_ms': 5424.829519237392, 'p90_e2el_ms': 7536.02239508182, 'p99_e2el_ms': 10502.547446722165, 'scheduler': 'rr.Scheduler', 'offload': '20', 'kvmem': '0.3', 'test_case': 'share'}, {'date': '20260416-150848', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 134.95407235436141, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 0.2222978490135979, 'request_goodput': None, 'output_throughput': 422.365913125836, 'total_token_throughput': 423.477402370904, 'mean_ttft_ms': 58.810384913037225, 'median_ttft_ms': 59.570037527009845, 'std_ttft_ms': 9.167482861137126, 'p50_ttft_ms': 59.570037527009845, 'p75_ttft_ms': 64.63468668516725, 'p90_ttft_ms': 70.3165796585381, 'p99_ttft_ms': 73.14221364445984, 'mean_tpot_ms': 40.649831477141994, 'median_tpot_ms': 38.866795573345314, 'std_tpot_ms': 17.468152606473076, 'p50_tpot_ms': 38.866795573345314, 'p75_tpot_ms': 56.569821163624525, 'p90_tpot_ms': 62.91113585472037, 'p99_tpot_ms': 70.68194164974706, 'mean_itl_ms': 40.649831530827505, 'median_itl_ms': 16.14886592142284, 'std_itl_ms': 1103.7788181454625, 'p50_itl_ms': 16.14886592142284, 'p75_itl_ms': 16.350711695849895, 'p90_itl_ms': 16.575566213577986, 'p99_itl_ms': 17.160390578210354, 'mean_e2el_ms': 77252.84036000569, 'median_e2el_ms': 73872.52119020559, 'std_e2el_ms': 33170.93227714694, 'p50_e2el_ms': 73872.52119020559, 'p75_e2el_ms': 107485.20166112576, 'p90_e2el_ms': 119520.40259093048, 'p99_e2el_ms': 134273.83558119182, 'scheduler': 'fcfs.Scheduler', 'offload': '20', 'kvmem': '0.3', 'test_case': 'throughput'}, {'date': '20260416-150916', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 12.122502525802702, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6392, 'request_throughput': 2.4747365435598065, 'request_goodput': None, 'output_throughput': 527.2838662144761, 'total_token_throughput': 1065.3740820024966, 'mean_ttft_ms': 155.05732687500614, 'median_ttft_ms': 148.27992743812501, 'std_ttft_ms': 64.9017270394078, 'p50_ttft_ms': 148.27992743812501, 'p75_ttft_ms': 187.0567554142326, 'p90_ttft_ms': 247.44337191805243, 'p99_ttft_ms': 250.46362956520167, 'mean_tpot_ms': 18.684161192461822, 'median_tpot_ms': 16.562727524031853, 'std_tpot_ms': 6.1562045449455525, 'p50_tpot_ms': 16.562727524031853, 'p75_tpot_ms': 18.129110572081576, 'p90_tpot_ms': 20.724867318164215, 'p99_tpot_ms': 42.05165314907207, 'mean_itl_ms': 16.373502547085327, 'median_itl_ms': 15.990654239431024, 'std_itl_ms': 7.2306412313688835, 'p50_itl_ms': 15.990654239431024, 'p75_itl_ms': 16.333472914993763, 'p90_itl_ms': 16.60124217160046, 'p99_itl_ms': 16.92937550600618, 'mean_e2el_ms': 3627.3312513250858, 'median_e2el_ms': 2495.6588419154286, 'std_e2el_ms': 3277.9785958033017, 'p50_e2el_ms': 2495.6588419154286, 'p75_e2el_ms': 5425.372816622257, 'p90_e2el_ms': 7620.813495898623, 'p99_e2el_ms': 12000.379805788398, 'scheduler': 'fcfs.Scheduler', 'offload': '20', 'kvmem': '0.3', 'test_case': 'share'}, {'date': '20260416-151322', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 12.088397333398461, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6394, 'request_throughput': 2.4817185581015293, 'request_goodput': None, 'output_throughput': 528.9369486833726, 'total_token_throughput': 1068.5452871665818, 'mean_ttft_ms': 151.95083615059653, 'median_ttft_ms': 133.3352120127529, 'std_ttft_ms': 71.58818330841096, 'p50_ttft_ms': 133.3352120127529, 'p75_ttft_ms': 199.06491902656853, 'p90_ttft_ms': 246.93884905427694, 'p99_ttft_ms': 250.03856548573822, 'mean_tpot_ms': 18.751943067843065, 'median_tpot_ms': 16.32699986327101, 'std_tpot_ms': 6.506964286112364, 'p50_tpot_ms': 16.32699986327101, 'p75_tpot_ms': 17.970820617241163, 'p90_tpot_ms': 20.18275537358766, 'p99_tpot_ms': 42.13935153465718, 'mean_itl_ms': 16.371859606992896, 'median_itl_ms': 15.978627372533083, 'std_itl_ms': 7.241187677562636, 'p50_itl_ms': 15.978627372533083, 'p75_itl_ms': 16.296447487547994, 'p90_itl_ms': 16.519087739288807, 'p99_itl_ms': 16.940927947871387, 'mean_e2el_ms': 3624.967801462238, 'median_e2el_ms': 2495.0108071789145, 'std_e2el_ms': 3273.0213555154282, 'p50_e2el_ms': 2495.0108071789145, 'p75_e2el_ms': 5419.294910505414, 'p90_e2el_ms': 7614.791301172229, 'p99_e2el_ms': 11983.961589601822, 'scheduler': 'rr.Scheduler', 'offload': '4', 'kvmem': '0.3', 'test_case': 'share'}]


data = [{'date': '20260418-001803', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 124.02743248804472, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 0.24188197238455103, 'request_goodput': None, 'output_throughput': 459.57574753064694, 'total_token_throughput': 460.7851573925697, 'mean_ttft_ms': 37.43398720398545, 'median_ttft_ms': 36.516911000944674, 'std_ttft_ms': 4.463038332965506, 'p50_ttft_ms': 36.516911000944674, 'p75_ttft_ms': 41.14477784605697, 'p90_ttft_ms': 43.07851979974658, 'p99_ttft_ms': 45.49924946157262, 'mean_tpot_ms': 40.11311363164408, 'median_tpot_ms': 38.13703301688337, 'std_tpot_ms': 15.429276307029175, 'p50_tpot_ms': 38.13703301688337, 'p75_tpot_ms': 52.6477739226177, 'p90_tpot_ms': 63.645428538422, 'p99_tpot_ms': 65.19651811510832, 'mean_itl_ms': 40.11311373573332, 'median_itl_ms': 18.073188955895603, 'std_itl_ms': 1037.91167646519, 'p50_itl_ms': 18.073188955895603, 'p75_itl_ms': 19.13920236984268, 'p90_itl_ms': 19.479449023492634, 'p99_itl_ms': 19.911838199477643, 'mean_e2el_ms': 76212.2367736961, 'median_e2el_ms': 72455.22353157867, 'std_e2el_ms': 29302.498225924468, 'p50_e2el_ms': 72455.22353157867, 'p75_e2el_ms': 100019.48848960456, 'p90_e2el_ms': 120905.1516442094, 'p99_e2el_ms': 123850.69612666266, 'scheduler': 'fcfs.Scheduler', 'offload': '4', 'kvmem': '0.3', 'test_case': 'throughput'}, {'date': '20260418-001832', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 12.774213800905272, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6390, 'request_throughput': 2.3484811251455637, 'request_goodput': None, 'output_throughput': 500.22647965600504, 'total_token_throughput': 1010.8645589668221, 'mean_ttft_ms': 312.9450419529652, 'median_ttft_ms': 307.76762298773974, 'std_ttft_ms': 183.88338146985322, 'p50_ttft_ms': 307.76762298773974, 'p75_ttft_ms': 470.4702669987455, 'p90_ttft_ms': 568.2771407999098, 'p99_ttft_ms': 570.604970313143, 'mean_tpot_ms': 26.39655168712289, 'median_tpot_ms': 20.188488264439926, 'std_tpot_ms': 18.60050273315021, 'p50_tpot_ms': 20.188488264439926, 'p75_tpot_ms': 22.650660893666636, 'p90_tpot_ms': 30.924652933820386, 'p99_tpot_ms': 96.00387902068903, 'mean_itl_ms': 19.416324033529303, 'median_itl_ms': 19.135370501317084, 'std_itl_ms': 17.271791349075983, 'p50_itl_ms': 19.135370501317084, 'p75_itl_ms': 19.448779115919024, 'p90_itl_ms': 19.65270407963544, 'p99_itl_ms': 20.088758694473654, 'mean_e2el_ms': 4429.205600412873, 'median_e2el_ms': 3243.519910960458, 'std_e2el_ms': 3556.6992072929634, 'p50_e2el_ms': 3243.519910960458, 'p75_e2el_ms': 6747.125003661495, 'p90_e2el_ms': 9259.170878445731, 'p99_e2el_ms': 12653.616877356544, 'scheduler': 'fcfs.Scheduler', 'offload': '4', 'kvmem': '0.3', 'test_case': 'share'}, {'date': '20260418-003923', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 159.50432973192073, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 0.18808266866749676, 'request_goodput': None, 'output_throughput': 357.3570704682438, 'total_token_throughput': 358.29748381158134, 'mean_ttft_ms': 39.90324072074145, 'median_ttft_ms': 40.44702497776598, 'std_ttft_ms': 5.133682240413675, 'p50_ttft_ms': 40.44702497776598, 'p75_ttft_ms': 43.952228617854416, 'p90_ttft_ms': 46.48804794996977, 'p99_ttft_ms': 47.62484097154811, 'mean_tpot_ms': 78.71446108441194, 'median_tpot_ms': 79.41303779042497, 'std_tpot_ms': 3.9035494125792582, 'p50_tpot_ms': 79.41303779042497, 'p75_tpot_ms': 82.01805312941615, 'p90_tpot_ms': 83.17818411969468, 'p99_tpot_ms': 83.81310344256583, 'mean_itl_ms': 78.71446118060119, 'median_itl_ms': 18.767807516269386, 'std_itl_ms': 1091.3142123718449, 'p50_itl_ms': 18.767807516269386, 'p75_itl_ms': 19.297679013106972, 'p90_itl_ms': 19.536800985224545, 'p99_itl_ms': 27.931604853365567, 'mean_e2el_ms': 149518.664840019, 'median_e2el_ms': 150844.36254750472, 'std_e2el_ms': 7411.88948486726, 'p50_e2el_ms': 150844.36254750472, 'p75_e2el_ms': 155797.1215112484, 'p90_e2el_ms': 157999.66691015288, 'p99_e2el_ms': 159192.22043349175, 'scheduler': 'rr.Scheduler', 'offload': '4', 'kvmem': '0.3', 'test_case': 'throughput'}, {'date': '20260418-004558', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 121.10130247403868, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 0.24772648507584225, 'request_goodput': None, 'output_throughput': 470.6803216441003, 'total_token_throughput': 471.91895406947947, 'mean_ttft_ms': 38.785496967223786, 'median_ttft_ms': 38.35868835449219, 'std_ttft_ms': 5.081502305266202, 'p50_ttft_ms': 38.35868835449219, 'p75_ttft_ms': 41.89480422064662, 'p90_ttft_ms': 46.29413990769535, 'p99_ttft_ms': 47.828356893733144, 'mean_tpot_ms': 60.13044265322587, 'median_tpot_ms': 60.18425018431961, 'std_tpot_ms': 2.1830616187742997, 'p50_tpot_ms': 60.18425018431961, 'p75_tpot_ms': 61.837053360511156, 'p90_tpot_ms': 62.94798858208987, 'p99_tpot_ms': 63.528170331040165, 'mean_itl_ms': 60.14099936190668, 'median_itl_ms': 18.486839020624757, 'std_itl_ms': 736.6690689527901, 'p50_itl_ms': 18.486839020624757, 'p75_itl_ms': 19.27773602074012, 'p90_itl_ms': 19.556746049784124, 'p99_itl_ms': 21.306486085522916, 'mean_e2el_ms': 114226.49609544314, 'median_e2el_ms': 114330.7159364922, 'std_e2el_ms': 4145.755124237097, 'p50_e2el_ms': 114330.7159364922, 'p75_e2el_ms': 117465.50296939677, 'p90_e2el_ms': 119576.61746267695, 'p99_e2el_ms': 120679.22326652333, 'scheduler': 'rr.Scheduler', 'offload': '20', 'kvmem': '0.3', 'test_case': 'throughput'}, {'date': '20260418-004629', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 13.548301476053894, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6390, 'request_throughput': 2.2142997078286055, 'request_goodput': None, 'output_throughput': 471.64583776749294, 'total_token_throughput': 953.1084042396927, 'mean_ttft_ms': 309.14397496574867, 'median_ttft_ms': 351.95747553370893, 'std_ttft_ms': 181.4469497506518, 'p50_ttft_ms': 351.95747553370893, 'p75_ttft_ms': 515.3724934789352, 'p90_ttft_ms': 540.3721646638587, 'p99_ttft_ms': 545.2990929665975, 'mean_tpot_ms': 25.434514833105705, 'median_tpot_ms': 19.9475444375735, 'std_tpot_ms': 15.149840706523774, 'p50_tpot_ms': 19.9475444375735, 'p75_tpot_ms': 23.742313756990956, 'p90_tpot_ms': 30.666333027395662, 'p99_tpot_ms': 82.66178783588109, 'mean_itl_ms': 19.668248768767, 'median_itl_ms': 19.054610980674624, 'std_itl_ms': 16.503791297569613, 'p50_itl_ms': 19.054610980674624, 'p75_itl_ms': 19.424410245846957, 'p90_itl_ms': 19.622421078383923, 'p99_itl_ms': 20.00392655376345, 'mean_e2el_ms': 4478.812560245085, 'median_e2el_ms': 3220.7187740132213, 'std_e2el_ms': 3726.3124370156465, 'p50_e2el_ms': 3220.7187740132213, 'p75_e2el_ms': 6699.2895571747795, 'p90_e2el_ms': 9286.29310112447, 'p99_e2el_ms': 13446.733740093186, 'scheduler': 'rr.Scheduler', 'offload': '20', 'kvmem': '0.3', 'test_case': 'share'}, {'date': '20260418-002444', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 125.1029916240368, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 0.2398024188754565, 'request_goodput': None, 'output_throughput': 455.62459586336735, 'total_token_throughput': 456.8236079577446, 'mean_ttft_ms': 37.32040509736787, 'median_ttft_ms': 37.69095300231129, 'std_ttft_ms': 4.132914754379143, 'p50_ttft_ms': 37.69095300231129, 'p75_ttft_ms': 40.30156705994159, 'p90_ttft_ms': 41.71439209021628, 'p99_ttft_ms': 45.2281686081551, 'mean_tpot_ms': 40.09547053459228, 'median_tpot_ms': 37.42718575807978, 'std_tpot_ms': 15.656904902854482, 'p50_tpot_ms': 37.42718575807978, 'p75_tpot_ms': 56.06225627535668, 'p90_tpot_ms': 62.407678124183924, 'p99_tpot_ms': 65.59676590324842, 'mean_itl_ms': 40.09547063007043, 'median_itl_ms': 18.104222021065652, 'std_itl_ms': 1073.52854080287, 'p50_itl_ms': 18.104222021065652, 'p75_itl_ms': 19.110189750790596, 'p90_itl_ms': 19.60433921776712, 'p99_itl_ms': 20.121504000853747, 'mean_e2el_ms': 76178.61895028813, 'median_e2el_ms': 71110.94996309839, 'std_e2el_ms': 29734.389606629422, 'p50_e2el_ms': 71110.94996309839, 'p75_e2el_ms': 106503.90761828749, 'p90_e2el_ms': 118551.68067386841, 'p99_e2el_ms': 124610.26367719751, 'scheduler': 'fcfs.Scheduler', 'offload': '20', 'kvmem': '0.3', 'test_case': 'throughput'}, {'date': '20260418-002515', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 14.539910671068355, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6390, 'request_throughput': 2.0632864037943692, 'request_goodput': None, 'output_throughput': 439.48000400820064, 'total_token_throughput': 888.1072444065563, 'mean_ttft_ms': 327.5701089839761, 'median_ttft_ms': 368.0688514141366, 'std_ttft_ms': 179.34268573765272, 'p50_ttft_ms': 368.0688514141366, 'p75_ttft_ms': 530.870322487317, 'p90_ttft_ms': 541.7455928167328, 'p99_ttft_ms': 564.2935117683373, 'mean_tpot_ms': 25.618597233532476, 'median_tpot_ms': 19.988060544799925, 'std_tpot_ms': 15.261673376808432, 'p50_tpot_ms': 19.988060544799925, 'p75_tpot_ms': 23.865418017552305, 'p90_tpot_ms': 30.80889634068377, 'p99_tpot_ms': 83.30221029929814, 'mean_itl_ms': 20.000669259084507, 'median_itl_ms': 19.11472447682172, 'std_itl_ms': 16.672133323894258, 'p50_itl_ms': 19.11472447682172, 'p75_itl_ms': 19.3557515158318, 'p90_itl_ms': 19.577039941214025, 'p99_itl_ms': 19.992207544855766, 'mean_e2el_ms': 4567.7118032549815, 'median_e2el_ms': 3234.0856390073895, 'std_e2el_ms': 3891.7052702466613, 'p50_e2el_ms': 3234.0856390073895, 'p75_e2el_ms': 6735.723216028418, 'p90_e2el_ms': 9337.430013157431, 'p99_e2el_ms': 14435.837455787696, 'scheduler': 'fcfs.Scheduler', 'offload': '20', 'kvmem': '0.3', 'test_case': 'share'}, {'date': '20260418-003953', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 13.535574097186327, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6390, 'request_throughput': 2.216381793974751, 'request_goodput': None, 'output_throughput': 472.08932211662193, 'total_token_throughput': 954.0046035198652, 'mean_ttft_ms': 339.5855613828947, 'median_ttft_ms': 385.2144534466788, 'std_ttft_ms': 181.73405446999945, 'p50_ttft_ms': 385.2144534466788, 'p75_ttft_ms': 546.8036982347257, 'p90_ttft_ms': 572.9726209538057, 'p99_ttft_ms': 577.2769663855433, 'mean_tpot_ms': 25.87500204683043, 'median_tpot_ms': 20.104530345027644, 'std_tpot_ms': 16.360702332062786, 'p50_tpot_ms': 20.104530345027644, 'p75_tpot_ms': 23.98279026339326, 'p90_tpot_ms': 30.716841547771093, 'p99_tpot_ms': 86.25225730426607, 'mean_itl_ms': 19.658671881389985, 'median_itl_ms': 19.04007059056312, 'std_itl_ms': 15.989615368535551, 'p50_itl_ms': 19.04007059056312, 'p75_itl_ms': 19.429556385148317, 'p90_itl_ms': 19.671333068981767, 'p99_itl_ms': 20.121044367551804, 'mean_e2el_ms': 4507.22388458283, 'median_e2el_ms': 3256.7202844657004, 'std_e2el_ms': 3724.6188408199687, 'p50_e2el_ms': 3256.7202844657004, 'p75_e2el_ms': 6734.378752007615, 'p90_e2el_ms': 9319.99133920763, 'p99_e2el_ms': 13441.277511115188, 'scheduler': 'rr.Scheduler', 'offload': '4', 'kvmem': '0.3', 'test_case': 'share'}, {'date': '20260418-001144', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 129.95789212803356, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 0.23084400269007302, 'request_goodput': None, 'output_throughput': 438.60360511113873, 'total_token_throughput': 439.7578251245891, 'mean_ttft_ms': 41.60589191596955, 'median_ttft_ms': 41.813412914052606, 'std_ttft_ms': 6.2454713737517435, 'p50_ttft_ms': 41.813412914052606, 'p75_ttft_ms': 46.289868594612926, 'p90_ttft_ms': 48.73080076649785, 'p99_ttft_ms': 51.9961726013571, 'mean_tpot_ms': 43.203591730149576, 'median_tpot_ms': 43.56607547205917, 'std_tpot_ms': 15.533908825105556, 'p50_tpot_ms': 43.56607547205917, 'p75_tpot_ms': 56.994573385361534, 'p90_tpot_ms': 61.91339919446826, 'p99_tpot_ms': 67.92354467986623, 'mean_itl_ms': 43.20359187496884, 'median_itl_ms': 18.59009708277881, 'std_itl_ms': 1235.5242035475787, 'p50_itl_ms': 18.59009708277881, 'p75_itl_ms': 19.170047424267977, 'p90_itl_ms': 19.42718585487455, 'p99_itl_ms': 19.981032798532397, 'mean_e2el_ms': 82085.22658747001, 'median_e2el_ms': 82770.95198945608, 'std_e2el_ms': 29503.282435423895, 'p50_e2el_ms': 82770.95198945608, 'p75_e2el_ms': 108280.00827570213, 'p90_e2el_ms': 117624.08768103924, 'p99_e2el_ms': 129032.642968609, 'scheduler': 'fcfs.Scheduler', 'offload': 'none', 'kvmem': '0.3', 'test_case': 'throughput'}, {'date': '20260418-001213', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 12.686591814970598, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6390, 'request_throughput': 2.3647012875908096, 'request_goodput': None, 'output_throughput': 503.68137425684245, 'total_token_throughput': 1017.8462575553375, 'mean_ttft_ms': 317.6794379561519, 'median_ttft_ms': 291.5401983773336, 'std_ttft_ms': 179.84954199425448, 'p50_ttft_ms': 291.5401983773336, 'p75_ttft_ms': 454.4470337568782, 'p90_ttft_ms': 553.1369978096336, 'p99_ttft_ms': 555.1649463037029, 'mean_tpot_ms': 26.368247205323655, 'median_tpot_ms': 19.98701108224643, 'std_tpot_ms': 18.93559708730804, 'p50_tpot_ms': 19.98701108224643, 'p75_tpot_ms': 22.7534271922546, 'p90_tpot_ms': 31.231136288790182, 'p99_tpot_ms': 97.16016388987188, 'mean_itl_ms': 19.268108629614247, 'median_itl_ms': 19.06385598704219, 'std_itl_ms': 16.385140541470353, 'p50_itl_ms': 19.06385598704219, 'p75_itl_ms': 19.428781524766237, 'p90_itl_ms': 19.64087109081447, 'p99_itl_ms': 20.124051021412015, 'mean_e2el_ms': 4402.51834608304, 'median_e2el_ms': 3230.893748579547, 'std_e2el_ms': 3536.3857480809493, 'p50_e2el_ms': 3230.893748579547, 'p75_e2el_ms': 6728.717310121283, 'p90_e2el_ms': 9226.411270792598, 'p99_e2el_ms': 12538.628402007744, 'scheduler': 'fcfs.Scheduler', 'offload': 'none', 'kvmem': '0.3', 'test_case': 'share'}, {'date': '20260418-004223', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 14.521199543960392, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6390, 'request_throughput': 2.0659450281073712, 'request_goodput': None, 'output_throughput': 440.0462909868701, 'total_token_throughput': 889.2516049316829, 'mean_ttft_ms': 309.69831720770645, 'median_ttft_ms': 283.88564905617386, 'std_ttft_ms': 184.13425435692318, 'p50_ttft_ms': 283.88564905617386, 'p75_ttft_ms': 522.8188794571906, 'p90_ttft_ms': 534.1159142553806, 'p99_ttft_ms': 556.7404755600728, 'mean_tpot_ms': 25.594744168089427, 'median_tpot_ms': 20.124137655577876, 'std_tpot_ms': 15.237065679398917, 'p50_tpot_ms': 20.124137655577876, 'p75_tpot_ms': 23.744386562122767, 'p90_tpot_ms': 30.792373294455242, 'p99_tpot_ms': 83.18091431469652, 'mean_itl_ms': 19.996778797739005, 'median_itl_ms': 19.020843086764216, 'std_itl_ms': 16.930174883908506, 'p50_itl_ms': 19.020843086764216, 'p75_itl_ms': 19.37266462482512, 'p90_itl_ms': 19.617359898984432, 'p99_itl_ms': 20.004539070650935, 'mean_e2el_ms': 4549.015279610952, 'median_e2el_ms': 3219.064402510412, 'std_e2el_ms': 3882.2120536643706, 'p50_e2el_ms': 3219.064402510412, 'p75_e2el_ms': 6704.833458759822, 'p90_e2el_ms': 9309.04449115042, 'p99_e2el_ms': 14397.431656976696, 'scheduler': 'rr.Scheduler', 'offload': '4', 'kvmem': '0.95', 'test_case': 'share'}, {'date': '20260418-003230', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 178.336667960044, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 0.16822115352475603, 'request_goodput': None, 'output_throughput': 319.62019169703643, 'total_token_throughput': 320.4612974646602, 'mean_ttft_ms': 37.777967494912446, 'median_ttft_ms': 38.60034351237118, 'std_ttft_ms': 5.369271847543192, 'p50_ttft_ms': 38.60034351237118, 'p75_ttft_ms': 42.08760353503749, 'p90_ttft_ms': 44.59204473532736, 'p99_ttft_ms': 45.642650285735726, 'mean_tpot_ms': 84.99936392040044, 'median_tpot_ms': 85.11889027909774, 'std_tpot_ms': 5.437190778827847, 'p50_tpot_ms': 85.11889027909774, 'p75_tpot_ms': 89.27264700331929, 'p90_tpot_ms': 92.18104240523034, 'p99_tpot_ms': 93.543441473052, 'mean_itl_ms': 84.9993640151838, 'median_itl_ms': 19.09212756436318, 'std_itl_ms': 1050.5668109760043, 'p50_itl_ms': 19.09212756436318, 'p75_itl_ms': 19.491639861371368, 'p90_itl_ms': 19.809418148361146, 'p99_itl_ms': 132.80079971533266, 'mean_e2el_ms': 161451.57005233533, 'median_e2el_ms': 161677.02686751727, 'std_e2el_ms': 10323.237968756193, 'p50_e2el_ms': 161677.02686751727, 'p75_e2el_ms': 169570.62177581247, 'p90_e2el_ms': 175085.35330581944, 'p99_e2el_ms': 177669.36801531818, 'scheduler': 'rr.Scheduler', 'offload': 'none', 'kvmem': '0.3', 'test_case': 'throughput'}, {'date': '20260418-003301', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 14.521886915899813, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6390, 'request_throughput': 2.065847239669207, 'request_goodput': None, 'output_throughput': 440.02546204954103, 'total_token_throughput': 889.2095135282823, 'mean_ttft_ms': 336.5393814941247, 'median_ttft_ms': 363.11373952776194, 'std_ttft_ms': 171.02333418931113, 'p50_ttft_ms': 363.11373952776194, 'p75_ttft_ms': 522.2715316340327, 'p90_ttft_ms': 550.3836517222226, 'p99_ttft_ms': 555.2627910696901, 'mean_tpot_ms': 25.42476667345299, 'median_tpot_ms': 19.963775529190325, 'std_tpot_ms': 15.25009686936668, 'p50_tpot_ms': 19.963775529190325, 'p75_tpot_ms': 23.766141081879656, 'p90_tpot_ms': 28.610161439024104, 'p99_tpot_ms': 83.21106277452779, 'mean_itl_ms': 19.913153220832044, 'median_itl_ms': 19.022372900508344, 'std_itl_ms': 26.77593004315256, 'p50_itl_ms': 19.022372900508344, 'p75_itl_ms': 19.428709580097347, 'p90_itl_ms': 19.785031164065003, 'p99_itl_ms': 20.399799656588584, 'mean_e2el_ms': 4558.127664634958, 'median_e2el_ms': 3234.2377855675295, 'std_e2el_ms': 3887.9669108719813, 'p50_e2el_ms': 3234.2377855675295, 'p75_e2el_ms': 6713.588995218743, 'p90_e2el_ms': 9319.22881342471, 'p99_e2el_ms': 14423.144535385072, 'scheduler': 'rr.Scheduler', 'offload': 'none', 'kvmem': '0.3', 'test_case': 'share'}, {'date': '20260417-235425', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 88.71181898098439, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 0.3381736542504058, 'request_goodput': None, 'output_throughput': 642.529943075771, 'total_token_throughput': 644.220811347023, 'mean_ttft_ms': 40.31100538559258, 'median_ttft_ms': 40.15557561069727, 'std_ttft_ms': 6.1372030667198585, 'p50_ttft_ms': 40.15557561069727, 'p75_ttft_ms': 45.392814790830016, 'p90_ttft_ms': 48.92194978892803, 'p99_ttft_ms': 50.431844079867005, 'mean_tpot_ms': 26.687753399456735, 'median_tpot_ms': 25.758238297739037, 'std_tpot_ms': 11.456743089860044, 'p50_tpot_ms': 25.758238297739037, 'p75_tpot_ms': 37.0143353464874, 'p90_tpot_ms': 41.16684722507166, 'p99_tpot_ms': 46.28349126611354, 'mean_itl_ms': 26.68775350898563, 'median_itl_ms': 10.241345502436161, 'std_itl_ms': 718.6964723574323, 'p50_itl_ms': 10.241345502436161, 'p75_itl_ms': 10.451107460539788, 'p90_itl_ms': 10.930746933445334, 'p99_itl_ms': 12.009569727815688, 'mean_e2el_ms': 50720.354710953936, 'median_e2el_ms': 48952.97244959511, 'std_e2el_ms': 21761.16955139931, 'p50_e2el_ms': 48952.97244959511, 'p75_e2el_ms': 70334.86785995774, 'p90_e2el_ms': 78225.07784548216, 'p99_e2el_ms': 87938.45702161548, 'scheduler': 'none', 'offload': 'none', 'kvmem': '0.3', 'test_case': 'throughput'}, {'date': '20260417-235456', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 8.073747884947807, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6394, 'request_throughput': 3.7157464448363733, 'request_goodput': None, 'output_throughput': 791.949425609459, 'total_token_throughput': 1599.8765609317145, 'mean_ttft_ms': 314.98142579415196, 'median_ttft_ms': 358.17459411919117, 'std_ttft_ms': 182.23438917324793, 'p50_ttft_ms': 358.17459411919117, 'p75_ttft_ms': 521.1219053599052, 'p90_ttft_ms': 548.4358995920047, 'p99_ttft_ms': 552.9895380325615, 'mean_tpot_ms': 16.962709436403618, 'median_tpot_ms': 11.615813332122512, 'std_tpot_ms': 15.20197246964834, 'p50_tpot_ms': 11.615813332122512, 'p75_tpot_ms': 15.178606963256398, 'p90_tpot_ms': 22.545764071930357, 'p99_tpot_ms': 74.26566242286933, 'mean_itl_ms': 11.25183290263988, 'median_itl_ms': 10.036231018602848, 'std_itl_ms': 12.423339071091162, 'p50_itl_ms': 10.036231018602848, 'p75_itl_ms': 10.462657548487186, 'p90_itl_ms': 11.644374649040401, 'p99_itl_ms': 30.771098709664574, 'mean_e2el_ms': 2701.8700555277364, 'median_e2el_ms': 2014.9668615777045, 'std_e2el_ms': 2069.318605135147, 'p50_e2el_ms': 2014.9668615777045, 'p75_e2el_ms': 3848.7294210353866, 'p90_e2el_ms': 5213.065737602303, 'p99_e2el_ms': 7973.800517714117, 'scheduler': 'none', 'offload': 'none', 'kvmem': '0.3', 'test_case': 'share'}, {'date': '20260417-235639', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 26.719204869121313, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 1.122787902819302, 'request_goodput': None, 'output_throughput': 2133.2970153566735, 'total_token_throughput': 2138.91095487077, 'mean_ttft_ms': 39.63781949132681, 'median_ttft_ms': 39.924815064296126, 'std_ttft_ms': 3.8059693224426177, 'p50_ttft_ms': 39.924815064296126, 'p75_ttft_ms': 42.44203498819843, 'p90_ttft_ms': 44.663595780730255, 'p99_ttft_ms': 45.95869701122865, 'mean_tpot_ms': 14.017171289625322, 'median_tpot_ms': 14.017957336749449, 'std_tpot_ms': 0.0026693080434301874, 'p50_tpot_ms': 14.017957336749449, 'p75_tpot_ms': 14.019894201386712, 'p90_tpot_ms': 14.020143755112803, 'p99_tpot_ms': 14.020267187022096, 'mean_itl_ms': 14.017171466735181, 'median_itl_ms': 13.997977948747575, 'std_itl_ms': 2.0372380485564388, 'p50_itl_ms': 13.997977948747575, 'p75_itl_ms': 15.860894345678389, 'p90_itl_ms': 16.826855251565576, 'p99_itl_ms': 17.531467045191675, 'mean_e2el_ms': 26658.246098489813, 'median_e2el_ms': 26659.205910516903, 'std_e2el_ms': 6.026765411696551, 'p50_e2el_ms': 26659.205910516903, 'p75_e2el_ms': 26662.203996558674, 'p90_e2el_ms': 26664.826904959045, 'p99_e2el_ms': 26665.85010827286, 'scheduler': 'none', 'offload': 'none', 'kvmem': '0.95', 'test_case': 'throughput'}, {'date': '20260417-235657', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 8.06188311893493, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6394, 'request_throughput': 3.721214951571185, 'request_goodput': None, 'output_throughput': 793.1149466782053, 'total_token_throughput': 1602.2311176481667, 'mean_ttft_ms': 322.9685923627888, 'median_ttft_ms': 363.85365354362875, 'std_ttft_ms': 182.80390809689345, 'p50_ttft_ms': 363.85365354362875, 'p75_ttft_ms': 528.8113676360808, 'p90_ttft_ms': 556.5440965350717, 'p99_ttft_ms': 560.9423039201647, 'mean_tpot_ms': 17.013080436665764, 'median_tpot_ms': 11.656030063614857, 'std_tpot_ms': 15.27547140071578, 'p50_tpot_ms': 11.656030063614857, 'p75_tpot_ms': 15.237981397434172, 'p90_tpot_ms': 22.605564927322444, 'p99_tpot_ms': 74.58893059846011, 'mean_itl_ms': 11.255858421906956, 'median_itl_ms': 10.048417025245726, 'std_itl_ms': 12.494696996422823, 'p50_itl_ms': 10.048417025245726, 'p75_itl_ms': 10.483724938239902, 'p90_itl_ms': 11.610604915767908, 'p99_itl_ms': 21.85328328283469, 'mean_e2el_ms': 2710.711245269825, 'median_e2el_ms': 2028.6487054545432, 'std_e2el_ms': 2067.9012311156043, 'p50_e2el_ms': 2028.6487054545432, 'p75_e2el_ms': 3857.9434728017077, 'p90_e2el_ms': 5211.066015274266, 'p99_e2el_ms': 7977.786233816296, 'scheduler': 'none', 'offload': 'none', 'kvmem': '0.95', 'test_case': 'share'}, {'date': '20260417-235940', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 88.76093487301841, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 0.33798652574939714, 'request_goodput': None, 'output_throughput': 642.1743989238546, 'total_token_throughput': 643.8643315526016, 'mean_ttft_ms': 44.60948531050235, 'median_ttft_ms': 40.8985570538789, 'std_ttft_ms': 10.631877280307082, 'p50_ttft_ms': 40.8985570538789, 'p75_ttft_ms': 55.61863712500781, 'p90_ttft_ms': 57.89070501923561, 'p99_ttft_ms': 61.65818187873811, 'mean_tpot_ms': 26.683402239185295, 'median_tpot_ms': 25.751476816704525, 'std_tpot_ms': 11.463182443623586, 'p50_tpot_ms': 25.751476816704525, 'p75_tpot_ms': 37.00308712950789, 'p90_tpot_ms': 41.17340745178521, 'p99_tpot_ms': 46.309658420447995, 'mean_itl_ms': 26.68340233589768, 'median_itl_ms': 10.23844548035413, 'std_itl_ms': 718.499877420935, 'p50_itl_ms': 10.23844548035413, 'p75_itl_ms': 10.471087414771318, 'p90_itl_ms': 10.913622914813459, 'p99_itl_ms': 11.74412014428526, 'mean_e2el_ms': 50716.390337523386, 'median_e2el_ms': 48940.81496447325, 'std_e2el_ms': 21777.35868568038, 'p50_e2el_ms': 48940.81496447325, 'p75_e2el_ms': 70327.56937545491, 'p90_e2el_ms': 78239.58841057029, 'p99_e2el_ms': 87998.42397442553, 'scheduler': 'none', 'offload': '4', 'kvmem': '0.3', 'test_case': 'throughput'}, {'date': '20260418-000003', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 8.084407373098657, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6394, 'request_throughput': 3.710847142590411, 'request_goodput': None, 'output_throughput': 790.9052209907696, 'total_token_throughput': 1597.767084694678, 'mean_ttft_ms': 340.6167860996599, 'median_ttft_ms': 368.5685050440952, 'std_ttft_ms': 173.6029373855982, 'p50_ttft_ms': 368.5685050440952, 'p75_ttft_ms': 529.030850797426, 'p90_ttft_ms': 558.1011265981942, 'p99_ttft_ms': 562.8440858097747, 'mean_tpot_ms': 16.88767199452832, 'median_tpot_ms': 11.657642441541823, 'std_tpot_ms': 15.427568321745333, 'p50_tpot_ms': 11.657642441541823, 'p75_tpot_ms': 15.206972099918904, 'p90_tpot_ms': 20.654156048031926, 'p99_tpot_ms': 75.21045077475716, 'mean_itl_ms': 11.202993658944932, 'median_itl_ms': 10.033091064542532, 'std_itl_ms': 12.036155409873366, 'p50_itl_ms': 10.033091064542532, 'p75_itl_ms': 10.490921442396939, 'p90_itl_ms': 11.585747147910297, 'p99_itl_ms': 12.580374144017695, 'mean_e2el_ms': 2717.145002315131, 'median_e2el_ms': 2028.6551549797878, 'std_e2el_ms': 2074.3549477177935, 'p50_e2el_ms': 2028.6551549797878, 'p75_e2el_ms': 3864.924849884119, 'p90_e2el_ms': 5232.074539037423, 'p99_e2el_ms': 8001.120059967507, 'scheduler': 'none', 'offload': '4', 'kvmem': '0.3', 'test_case': 'share'}, {'date': '20260418-000152', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 26.827633125009015, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 1.11824997234041, 'request_goodput': None, 'output_throughput': 2124.6749474467792, 'total_token_throughput': 2130.266197308481, 'mean_ttft_ms': 46.007979242131114, 'median_ttft_ms': 47.69614397082478, 'std_ttft_ms': 12.825106656346556, 'p50_ttft_ms': 47.69614397082478, 'p75_ttft_ms': 58.31479583866894, 'p90_ttft_ms': 60.8817479107529, 'p99_ttft_ms': 63.47295315936208, 'mean_tpot_ms': 14.04142895728897, 'median_tpot_ms': 14.041011667505824, 'std_tpot_ms': 0.0028949891802873247, 'p50_tpot_ms': 14.041011667505824, 'p75_tpot_ms': 14.042904393019409, 'p90_tpot_ms': 14.045975531861892, 'p99_tpot_ms': 14.046130266322313, 'mean_itl_ms': 14.041429046984145, 'median_itl_ms': 14.056888059712946, 'std_itl_ms': 2.03886694186706, 'p50_itl_ms': 14.056888059712946, 'p75_itl_ms': 15.822295914404094, 'p90_itl_ms': 16.830587084405124, 'p99_itl_ms': 17.705288212746378, 'mean_e2el_ms': 26710.681569133885, 'median_e2el_ms': 26715.180453495122, 'std_e2el_ms': 13.217720764154402, 'p50_e2el_ms': 26715.180453495122, 'p75_e2el_ms': 26721.038883551955, 'p90_e2el_ms': 26723.9034330938, 'p99_e2el_ms': 26725.329464334063, 'scheduler': 'none', 'offload': '4', 'kvmem': '0.95', 'test_case': 'throughput'}, {'date': '20260418-000214', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 8.278623257065192, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6394, 'request_throughput': 3.623790945480847, 'request_goodput': None, 'output_throughput': 772.3506435134846, 'total_token_throughput': 1560.2835880925365, 'mean_ttft_ms': 313.4915671000878, 'median_ttft_ms': 329.38616711180657, 'std_ttft_ms': 175.79909686112447, 'p50_ttft_ms': 329.38616711180657, 'p75_ttft_ms': 492.30521614663303, 'p90_ttft_ms': 555.280796950683, 'p99_ttft_ms': 559.5898301783018, 'mean_tpot_ms': 17.56617858988697, 'median_tpot_ms': 11.429097283897654, 'std_tpot_ms': 16.90431047259947, 'p50_tpot_ms': 11.429097283897654, 'p75_tpot_ms': 15.187391285401057, 'p90_tpot_ms': 22.228271221845496, 'p99_tpot_ms': 81.08867816370909, 'mean_itl_ms': 11.311914977808685, 'median_itl_ms': 10.052900994196534, 'std_itl_ms': 12.299555747645526, 'p50_itl_ms': 10.052900994196534, 'p75_itl_ms': 10.48547012032941, 'p90_itl_ms': 11.59290699288249, 'p99_itl_ms': 12.416756369639188, 'mean_e2el_ms': 2713.1255900564915, 'median_e2el_ms': 2025.7405248703435, 'std_e2el_ms': 2076.1690580123095, 'p50_e2el_ms': 2025.7405248703435, 'p75_e2el_ms': 3861.895180423744, 'p90_e2el_ms': 5229.455047240483, 'p99_e2el_ms': 7999.6449856692925, 'scheduler': 'none', 'offload': '4', 'kvmem': '0.95', 'test_case': 'share'}, {'date': '20260418-000519', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 89.0304566458799, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 0.3369633396279825, 'request_goodput': None, 'output_throughput': 640.2303452931668, 'total_token_throughput': 641.9151619913067, 'mean_ttft_ms': 43.78293883831551, 'median_ttft_ms': 46.931691002100706, 'std_ttft_ms': 9.353936492637073, 'p50_ttft_ms': 46.931691002100706, 'p75_ttft_ms': 52.36213974421844, 'p90_ttft_ms': 53.93092650920153, 'p99_ttft_ms': 56.71564981341362, 'mean_tpot_ms': 26.691881471982317, 'median_tpot_ms': 25.732981788302002, 'std_tpot_ms': 11.468000626037604, 'p50_tpot_ms': 25.732981788302002, 'p75_tpot_ms': 36.976713148139915, 'p90_tpot_ms': 41.163132801429306, 'p99_tpot_ms': 46.35407885916143, 'mean_itl_ms': 26.725658083040198, 'median_itl_ms': 10.243140626698732, 'std_itl_ms': 727.1262849787936, 'p50_itl_ms': 10.243140626698732, 'p75_itl_ms': 10.447444801684469, 'p90_itl_ms': 10.970033006742597, 'p99_itl_ms': 11.764151337556541, 'mean_e2el_ms': 50731.665854132734, 'median_e2el_ms': 48920.04554648884, 'std_e2el_ms': 21784.90789874445, 'p50_e2el_ms': 48920.04554648884, 'p75_e2el_ms': 70269.8881548713, 'p90_e2el_ms': 78221.01683104411, 'p99_e2el_ms': 88075.31779577024, 'scheduler': 'none', 'offload': '20', 'kvmem': '0.3', 'test_case': 'throughput'}, {'date': '20260418-000543', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 8.207476251060143, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6394, 'request_throughput': 3.655203997224477, 'request_goodput': None, 'output_throughput': 779.0458119417768, 'total_token_throughput': 1573.809001071619, 'mean_ttft_ms': 342.3295277248447, 'median_ttft_ms': 306.87579652294517, 'std_ttft_ms': 182.23876096964804, 'p50_ttft_ms': 306.87579652294517, 'p75_ttft_ms': 471.8379407422617, 'p90_ttft_ms': 578.7800528109074, 'p99_ttft_ms': 580.7914491300471, 'mean_tpot_ms': 18.167776696500855, 'median_tpot_ms': 11.446377886882559, 'std_tpot_ms': 19.308625080424783, 'p50_tpot_ms': 11.446377886882559, 'p75_tpot_ms': 14.561335441267376, 'p90_tpot_ms': 23.480704181234923, 'p99_tpot_ms': 90.28381568915206, 'mean_itl_ms': 11.283719177569465, 'median_itl_ms': 10.04306087270379, 'std_itl_ms': 12.159127266680132, 'p50_itl_ms': 10.04306087270379, 'p75_itl_ms': 10.535727138631046, 'p90_itl_ms': 11.627217847853899, 'p99_itl_ms': 12.531948732212186, 'mean_e2el_ms': 2735.9822979196906, 'median_e2el_ms': 2051.9832700956613, 'std_e2el_ms': 2074.9892318286, 'p50_e2el_ms': 2051.9832700956613, 'p75_e2el_ms': 3888.1473094807006, 'p90_e2el_ms': 5245.584604330363, 'p99_e2el_ms': 8010.626824912615, 'scheduler': 'none', 'offload': '20', 'kvmem': '0.3', 'test_case': 'share'}, {'date': '20260418-000754', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 26.717644290067255, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 1.1228534849216858, 'request_goodput': None, 'output_throughput': 2133.421621351203, 'total_token_throughput': 2139.0358887758116, 'mean_ttft_ms': 44.7798947027574, 'median_ttft_ms': 45.12493743095547, 'std_ttft_ms': 10.880877469473567, 'p50_ttft_ms': 45.12493743095547, 'p75_ttft_ms': 54.78830978972837, 'p90_ttft_ms': 58.17870181053877, 'p99_ttft_ms': 60.48307390650735, 'mean_tpot_ms': 14.012301916175462, 'median_tpot_ms': 14.013011890964748, 'std_tpot_ms': 0.002334535821182692, 'p50_tpot_ms': 14.013011890964748, 'p75_tpot_ms': 14.013425462832403, 'p90_tpot_ms': 14.016148314851504, 'p99_tpot_ms': 14.016448144923322, 'mean_itl_ms': 14.012302004125532, 'median_itl_ms': 13.99356301408261, 'std_itl_ms': 2.0641572534658668, 'p50_itl_ms': 13.99356301408261, 'p75_itl_ms': 15.803824469912797, 'p90_itl_ms': 16.820165026001632, 'p99_itl_ms': 17.650062993634492, 'mean_e2el_ms': 26654.14123351996, 'median_e2el_ms': 26656.00718301721, 'std_e2el_ms': 8.156632377282529, 'p50_e2el_ms': 26656.00718301721, 'p75_e2el_ms': 26660.831596935168, 'p90_e2el_ms': 26663.39996175375, 'p99_e2el_ms': 26665.327426346485, 'scheduler': 'none', 'offload': '20', 'kvmem': '0.95', 'test_case': 'throughput'}, {'date': '20260418-000812', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 8.093190266983584, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6394, 'request_throughput': 3.7068200561632554, 'request_goodput': None, 'output_throughput': 790.0469146369285, 'total_token_throughput': 1596.033155515359, 'mean_ttft_ms': 342.1342610924815, 'median_ttft_ms': 367.88771057035774, 'std_ttft_ms': 175.1995034895138, 'p50_ttft_ms': 367.88771057035774, 'p75_ttft_ms': 529.3190891388804, 'p90_ttft_ms': 568.1091406615451, 'p99_ttft_ms': 573.2342672697268, 'mean_tpot_ms': 17.093353179127877, 'median_tpot_ms': 11.718511802068543, 'std_tpot_ms': 15.80931906156021, 'p50_tpot_ms': 11.718511802068543, 'p75_tpot_ms': 15.276073773602853, 'p90_tpot_ms': 21.1012317766694, 'p99_tpot_ms': 76.73560893232931, 'mean_itl_ms': 11.24500334572362, 'median_itl_ms': 10.0394815672189, 'std_itl_ms': 12.1139062464168, 'p50_itl_ms': 10.0394815672189, 'p75_itl_ms': 10.49087248975411, 'p90_itl_ms': 11.456053983420134, 'p99_itl_ms': 12.89376026019454, 'mean_e2el_ms': 2727.5741294802474, 'median_e2el_ms': 2038.66238205228, 'std_e2el_ms': 2075.9904048087838, 'p50_e2el_ms': 2038.66238205228, 'p75_e2el_ms': 3876.8582380143926, 'p90_e2el_ms': 5245.248864614407, 'p99_e2el_ms': 8014.396940320731, 'scheduler': 'none', 'offload': '20', 'kvmem': '0.95', 'test_case': 'share'}, {'date': '20260418-001411', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 42.68430515215732, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 0.7028344468314195, 'request_goodput': None, 'output_throughput': 1335.385448979697, 'total_token_throughput': 1338.899621213854, 'mean_ttft_ms': 30.58065685133139, 'median_ttft_ms': 31.323743984103203, 'std_ttft_ms': 3.7139658510410984, 'p50_ttft_ms': 31.323743984103203, 'p75_ttft_ms': 33.40469149406999, 'p90_ttft_ms': 34.49788254220039, 'p99_ttft_ms': 36.77194692427293, 'mean_tpot_ms': 22.435632738698693, 'median_tpot_ms': 22.43616595362098, 'std_tpot_ms': 0.001129217637645107, 'p50_tpot_ms': 22.43616595362098, 'p75_tpot_ms': 22.436344274828528, 'p90_tpot_ms': 22.436554211642044, 'p99_tpot_ms': 22.43659488085595, 'mean_itl_ms': 22.435632795216417, 'median_itl_ms': 22.42564898915589, 'std_itl_ms': 2.1954556838711077, 'p50_itl_ms': 22.42564898915589, 'p75_itl_ms': 24.386842793319374, 'p90_itl_ms': 25.43358588591218, 'p99_itl_ms': 26.316891405731436, 'mean_e2el_ms': 42635.847227640144, 'median_e2el_ms': 42637.07991200499, 'std_e2el_ms': 5.327157540436896, 'p50_e2el_ms': 42637.07991200499, 'p75_e2el_ms': 42639.789719716646, 'p90_e2el_ms': 42640.91897776816, 'p99_e2el_ms': 42643.06430784054, 'scheduler': 'fcfs.Scheduler', 'offload': 'none', 'kvmem': '0.95', 'test_case': 'throughput'}, {'date': '20260418-001441', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 14.525013881968334, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6390, 'request_throughput': 2.065402501077307, 'request_goodput': None, 'output_throughput': 439.93073272946634, 'total_token_throughput': 889.0180832137088, 'mean_ttft_ms': 325.9930875695621, 'median_ttft_ms': 366.9897373765707, 'std_ttft_ms': 177.83705989058174, 'p50_ttft_ms': 366.9897373765707, 'p75_ttft_ms': 528.1868315069005, 'p90_ttft_ms': 547.5069085368887, 'p99_ttft_ms': 552.0693788630888, 'mean_tpot_ms': 25.420559779391127, 'median_tpot_ms': 19.95367758223622, 'std_tpot_ms': 14.860547052239415, 'p50_tpot_ms': 19.95367758223622, 'p75_tpot_ms': 23.820077505416602, 'p90_tpot_ms': 30.406972498167296, 'p99_tpot_ms': 81.68062358605673, 'mean_itl_ms': 19.968533782294287, 'median_itl_ms': 19.113600021228194, 'std_itl_ms': 16.45673794333978, 'p50_itl_ms': 19.113600021228194, 'p75_itl_ms': 19.408468971960247, 'p90_itl_ms': 19.63918588589877, 'p99_itl_ms': 20.048866299912333, 'mean_e2el_ms': 4559.322077749917, 'median_e2el_ms': 3226.4929061057046, 'std_e2el_ms': 3892.034805850575, 'p50_e2el_ms': 3226.4929061057046, 'p75_e2el_ms': 6726.239779673051, 'p90_e2el_ms': 9325.89165142272, 'p99_e2el_ms': 14428.227717066184, 'scheduler': 'fcfs.Scheduler', 'offload': 'none', 'kvmem': '0.95', 'test_case': 'share'}, {'date': '20260418-002034', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 42.917372877011076, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 0.6990176236083095, 'request_goodput': None, 'output_throughput': 1328.133484855788, 'total_token_throughput': 1331.6285729738297, 'mean_ttft_ms': 38.84832848949979, 'median_ttft_ms': 37.57218294776976, 'std_ttft_ms': 6.183724848683002, 'p50_ttft_ms': 37.57218294776976, 'p75_ttft_ms': 44.26611453527585, 'p90_ttft_ms': 47.451112139970064, 'p99_ttft_ms': 49.91670957766473, 'mean_tpot_ms': 22.53285994796073, 'median_tpot_ms': 22.53292427561822, 'std_tpot_ms': 0.0023018213309696123, 'p50_tpot_ms': 22.53292427561822, 'p75_tpot_ms': 22.53320649624378, 'p90_tpot_ms': 22.535240990558485, 'p99_tpot_ms': 22.53889310912152, 'mean_itl_ms': 22.532860057837006, 'median_itl_ms': 21.719640004448593, 'std_itl_ms': 4.572251813294182, 'p50_itl_ms': 21.719640004448593, 'p75_itl_ms': 23.985620529856533, 'p90_itl_ms': 26.43818494398147, 'p99_itl_ms': 31.940065943636, 'mean_e2el_ms': 42828.74936966691, 'median_e2el_ms': 42829.724643495865, 'std_e2el_ms': 7.950202880317019, 'p50_e2el_ms': 42829.724643495865, 'p75_e2el_ms': 42833.30987690715, 'p90_e2el_ms': 42839.73407975864, 'p99_e2el_ms': 42842.717744701076, 'scheduler': 'fcfs.Scheduler', 'offload': '4', 'kvmem': '0.95', 'test_case': 'throughput'}, {'date': '20260418-002100', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 12.821072333958, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6390, 'request_throughput': 2.3398978820626217, 'request_goodput': None, 'output_throughput': 498.39824887933844, 'total_token_throughput': 1007.1700450358212, 'mean_ttft_ms': 319.3390089087188, 'median_ttft_ms': 360.00435007736087, 'std_ttft_ms': 178.67030721707175, 'p50_ttft_ms': 360.00435007736087, 'p75_ttft_ms': 522.8742287727073, 'p90_ttft_ms': 541.8141140136868, 'p99_ttft_ms': 546.7513384693302, 'mean_tpot_ms': 25.136260546740765, 'median_tpot_ms': 19.8369036956221, 'std_tpot_ms': 14.931288154179228, 'p50_tpot_ms': 19.8369036956221, 'p75_tpot_ms': 23.725352042644214, 'p90_tpot_ms': 30.394667652647254, 'p99_tpot_ms': 81.42023609555322, 'mean_itl_ms': 19.185013793088178, 'median_itl_ms': 19.02738190256059, 'std_itl_ms': 16.641077276816993, 'p50_itl_ms': 19.02738190256059, 'p75_itl_ms': 19.34291800716892, 'p90_itl_ms': 19.586167996749282, 'p99_itl_ms': 20.078969388268888, 'mean_e2el_ms': 4386.561802689297, 'median_e2el_ms': 3214.9542460683733, 'std_e2el_ms': 3529.816680139928, 'p50_e2el_ms': 3214.9542460683733, 'p75_e2el_ms': 6694.990976015106, 'p90_e2el_ms': 9169.139703921976, 'p99_e2el_ms': 12564.017377565617, 'scheduler': 'fcfs.Scheduler', 'offload': '4', 'kvmem': '0.95', 'test_case': 'share'}, {'date': '20260418-002736', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 42.77424531499855, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 0.7013566172605427, 'request_goodput': None, 'output_throughput': 1332.577572795031, 'total_token_throughput': 1336.0843558813337, 'mean_ttft_ms': 34.97167357709259, 'median_ttft_ms': 34.88257445860654, 'std_ttft_ms': 5.001179448413785, 'p50_ttft_ms': 34.88257445860654, 'p75_ttft_ms': 38.94550906261429, 'p90_ttft_ms': 41.92962618544698, 'p99_ttft_ms': 43.900238908827305, 'mean_tpot_ms': 22.47524644386816, 'median_tpot_ms': 22.47609120857151, 'std_tpot_ms': 0.0018285463456761699, 'p50_tpot_ms': 22.47609120857151, 'p75_tpot_ms': 22.47635356141127, 'p90_tpot_ms': 22.476622261810242, 'p99_tpot_ms': 22.477044340277267, 'mean_itl_ms': 22.475246545860806, 'median_itl_ms': 22.482650470919907, 'std_itl_ms': 2.216561522596102, 'p50_itl_ms': 22.482650470919907, 'p75_itl_ms': 24.453626887407154, 'p90_itl_ms': 25.475321989506483, 'p99_itl_ms': 26.34788995841518, 'mean_e2el_ms': 42715.46467048271, 'median_e2el_ms': 42716.588529525325, 'std_e2el_ms': 7.354145132885517, 'p50_e2el_ms': 42716.588529525325, 'p75_e2el_ms': 42721.54312575003, 'p90_e2el_ms': 42724.20868279878, 'p99_e2el_ms': 42726.059635002166, 'scheduler': 'fcfs.Scheduler', 'offload': '20', 'kvmem': '0.95', 'test_case': 'throughput'}, {'date': '20260418-002807', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 14.519179926952347, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6390, 'request_throughput': 2.066232400929903, 'request_goodput': None, 'output_throughput': 440.1075013980693, 'total_token_throughput': 889.3752997735945, 'mean_ttft_ms': 313.7287196625645, 'median_ttft_ms': 358.88261266518384, 'std_ttft_ms': 182.1064096472611, 'p50_ttft_ms': 358.88261266518384, 'p75_ttft_ms': 519.7558455402032, 'p90_ttft_ms': 531.6919805249199, 'p99_ttft_ms': 553.4101364994422, 'mean_tpot_ms': 25.616115952207032, 'median_tpot_ms': 19.997239005073066, 'std_tpot_ms': 15.249619919493114, 'p50_tpot_ms': 19.997239005073066, 'p75_tpot_ms': 23.77887357988966, 'p90_tpot_ms': 30.80066698656247, 'p99_tpot_ms': 83.26749690040013, 'mean_itl_ms': 20.02194175323173, 'median_itl_ms': 19.10706900525838, 'std_itl_ms': 16.539618979429928, 'p50_itl_ms': 19.10706900525838, 'p75_itl_ms': 19.399131298996508, 'p90_itl_ms': 19.630642072297633, 'p99_itl_ms': 20.211311609018594, 'mean_e2el_ms': 4558.380224330661, 'median_e2el_ms': 3224.0644823759794, 'std_e2el_ms': 3891.432411524471, 'p50_e2el_ms': 3224.0644823759794, 'p75_e2el_ms': 6728.656456049066, 'p90_e2el_ms': 9330.85756557994, 'p99_e2el_ms': 14418.000503862277, 'scheduler': 'fcfs.Scheduler', 'offload': '20', 'kvmem': '0.95', 'test_case': 'share'}, {'date': '20260418-003500', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 43.33075177320279, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 0.6923489386249934, 'request_goodput': None, 'output_throughput': 1315.4629833874874, 'total_token_throughput': 1318.9247280806123, 'mean_ttft_ms': 40.025111163655914, 'median_ttft_ms': 39.94222194887698, 'std_ttft_ms': 3.133148842117226, 'p50_ttft_ms': 39.94222194887698, 'p75_ttft_ms': 42.49006154714152, 'p90_ttft_ms': 44.00824997574091, 'p99_ttft_ms': 45.02438955241814, 'mean_tpot_ms': 22.743171268396637, 'median_tpot_ms': 22.744951796192694, 'std_tpot_ms': 0.002885651594620765, 'p50_tpot_ms': 22.744951796192694, 'p75_tpot_ms': 22.74513192557724, 'p90_tpot_ms': 22.745718322328933, 'p99_tpot_ms': 22.745743783020668, 'mean_itl_ms': 22.743171387766786, 'median_itl_ms': 22.62235153466463, 'std_itl_ms': 2.204304595604798, 'p50_itl_ms': 22.62235153466463, 'p75_itl_ms': 24.649470928125083, 'p90_itl_ms': 25.66141220740974, 'p99_itl_ms': 26.808650146704167, 'mean_e2el_ms': 43229.307349848874, 'median_e2el_ms': 43231.18559154682, 'std_e2el_ms': 7.291323605552252, 'p50_e2el_ms': 43231.18559154682, 'p75_e2el_ms': 43234.62916503195, 'p90_e2el_ms': 43237.132579809986, 'p99_e2el_ms': 43238.09506962076, 'scheduler': 'rr.Scheduler', 'offload': 'none', 'kvmem': '0.95', 'test_case': 'throughput'}, {'date': '20260418-003527', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 14.530604728031904, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6390, 'request_throughput': 2.0646078096202776, 'request_goodput': None, 'output_throughput': 439.76146344911916, 'total_token_throughput': 888.6760215208882, 'mean_ttft_ms': 337.8300640033558, 'median_ttft_ms': 364.87256607506424, 'std_ttft_ms': 170.99592305429334, 'p50_ttft_ms': 364.87256607506424, 'p75_ttft_ms': 523.5640184255317, 'p90_ttft_ms': 552.2366888821125, 'p99_ttft_ms': 556.2930296687409, 'mean_tpot_ms': 25.421637530681387, 'median_tpot_ms': 19.957718780011778, 'std_tpot_ms': 15.274091872374022, 'p50_tpot_ms': 19.957718780011778, 'p75_tpot_ms': 23.772750049829483, 'p90_tpot_ms': 28.631408212499473, 'p99_tpot_ms': 83.29462310974483, 'mean_itl_ms': 19.910706925563186, 'median_itl_ms': 19.055214594118297, 'std_itl_ms': 15.804966312780635, 'p50_itl_ms': 19.055214594118297, 'p75_itl_ms': 19.407626299653202, 'p90_itl_ms': 19.680599053390328, 'p99_itl_ms': 20.039862496778362, 'mean_e2el_ms': 4558.899803226814, 'median_e2el_ms': 3235.2529944619164, 'std_e2el_ms': 3887.663080031645, 'p50_e2el_ms': 3235.2529944619164, 'p75_e2el_ms': 6712.69976021722, 'p90_e2el_ms': 9317.471030191522, 'p99_e2el_ms': 14425.499953101391, 'scheduler': 'rr.Scheduler', 'offload': 'none', 'kvmem': '0.95', 'test_case': 'share'}, {'date': '20260418-004156', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 45.11194809200242, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 0.6650122920610136, 'request_goodput': None, 'output_throughput': 1263.523354915926, 'total_token_throughput': 1266.848416376231, 'mean_ttft_ms': 36.134183538767196, 'median_ttft_ms': 35.748858936131, 'std_ttft_ms': 5.591734839775666, 'p50_ttft_ms': 35.748858936131, 'p75_ttft_ms': 39.32919754879549, 'p90_ttft_ms': 43.503594351932406, 'p99_ttft_ms': 47.74350828723982, 'mean_tpot_ms': 23.706236696817285, 'median_tpot_ms': 23.706396736693577, 'std_tpot_ms': 0.0019021640176857535, 'p50_tpot_ms': 23.706396736693577, 'p75_tpot_ms': 23.70783779794657, 'p90_tpot_ms': 23.708644571869566, 'p99_tpot_ms': 23.708755511935436, 'mean_itl_ms': 23.706236767034294, 'median_itl_ms': 22.69838855136186, 'std_itl_ms': 6.002100985950279, 'p50_itl_ms': 22.69838855136186, 'p75_itl_ms': 26.202089269645512, 'p90_itl_ms': 29.193146037869155, 'p99_itl_ms': 36.83196861995384, 'mean_e2el_ms': 45054.27767079479, 'median_e2el_ms': 45054.315231973305, 'std_e2el_ms': 7.4648739743813275, 'p50_e2el_ms': 45054.315231973305, 'p75_e2el_ms': 45059.77829301264, 'p90_e2el_ms': 45062.766597559676, 'p99_e2el_ms': 45066.51572725037, 'scheduler': 'rr.Scheduler', 'offload': '4', 'kvmem': '0.95', 'test_case': 'throughput'}, {'date': '20260418-004851', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 43.16321611404419, 'completed': 30, 'total_input_tokens': 150, 'total_output_tokens': 57000, 'request_throughput': 0.6950362531080898, 'request_goodput': None, 'output_throughput': 1320.5688809053706, 'total_token_throughput': 1324.0440621709113, 'mean_ttft_ms': 39.12340439079951, 'median_ttft_ms': 39.9738815613091, 'std_ttft_ms': 4.562661082142736, 'p50_ttft_ms': 39.9738815613091, 'p75_ttft_ms': 42.09725302644074, 'p90_ttft_ms': 45.063909981399775, 'p99_ttft_ms': 47.177087906748056, 'mean_tpot_ms': 22.61376489831368, 'median_tpot_ms': 22.615112494194236, 'std_tpot_ms': 0.002315082100116562, 'p50_tpot_ms': 22.615112494194236, 'p75_tpot_ms': 22.615298207008426, 'p90_tpot_ms': 22.61543208838643, 'p99_tpot_ms': 22.61546662971235, 'mean_itl_ms': 22.61376499257801, 'median_itl_ms': 22.594682057388127, 'std_itl_ms': 2.279891659301198, 'p50_itl_ms': 22.594682057388127, 'p75_itl_ms': 24.64512741426006, 'p90_itl_ms': 25.742077035829425, 'p99_itl_ms': 26.504002609290183, 'mean_e2el_ms': 42982.662946288474, 'median_e2el_ms': 42984.88751100376, 'std_e2el_ms': 7.932917507703899, 'p50_e2el_ms': 42984.88751100376, 'p75_e2el_ms': 42988.40721586021, 'p90_e2el_ms': 42991.065114806406, 'p99_e2el_ms': 42993.37451136904, 'scheduler': 'rr.Scheduler', 'offload': '20', 'kvmem': '0.95', 'test_case': 'throughput'}, {'date': '20260418-004917', 'backend': 'vllm', 'model_id': 'llama-3.2-3B-Instruct', 'tokenizer_id': '/snfs1/llm-models/llama-3.2-3B-Instruct', 'num_prompts': 30, 'request_rate': 999.0, 'burstiness': 1.0, 'max_concurrency': 200, 'duration': 13.546524001983926, 'completed': 30, 'total_input_tokens': 6523, 'total_output_tokens': 6390, 'request_throughput': 2.2145902517580462, 'request_goodput': None, 'output_throughput': 471.7077236244639, 'total_token_throughput': 953.2334640317217, 'mean_ttft_ms': 311.41807214201737, 'median_ttft_ms': 302.31633747462183, 'std_ttft_ms': 166.17441814428585, 'p50_ttft_ms': 302.31633747462183, 'p75_ttft_ms': 386.707003810443, 'p90_ttft_ms': 543.3295244816691, 'p99_ttft_ms': 546.2556169368327, 'mean_tpot_ms': 25.060607965491883, 'median_tpot_ms': 20.03914265272518, 'std_tpot_ms': 14.175506774102155, 'p50_tpot_ms': 20.03914265272518, 'p75_tpot_ms': 23.64192502514188, 'p90_tpot_ms': 29.742076721529212, 'p99_tpot_ms': 78.83011489873749, 'mean_itl_ms': 19.6906296266155, 'median_itl_ms': 19.109425018541515, 'std_itl_ms': 17.32711202804738, 'p50_itl_ms': 19.109425018541515, 'p75_itl_ms': 19.420799682848155, 'p90_itl_ms': 19.6255249902606, 'p99_itl_ms': 20.147187700495124, 'mean_e2el_ms': 4485.8313686524825, 'median_e2el_ms': 3216.928548994474, 'std_e2el_ms': 3724.5587282561974, 'p50_e2el_ms': 3216.928548994474, 'p75_e2el_ms': 6714.864473440684, 'p90_e2el_ms': 9280.507812905129, 'p99_e2el_ms': 13448.845694197807, 'scheduler': 'rr.Scheduler', 'offload': '20', 'kvmem': '0.95', 'test_case': 'share'}]


df = pd.DataFrame(data)
df = df[df['scheduler'] != 'none']

print(df.columns)

test_cases = df['test_case'].unique()
print(test_cases)

df['scheduler'] = [a.replace('.Scheduler', '').upper() for a in df['scheduler']]
df['throughput'] = df['total_token_throughput']

# print(df)

# rtx 3090 kvmem 0.29
# (EngineCore_DP0 pid=2147573) INFO 04-13 13:02:23 [kv_cache_utils.py:1307] GPU KV cache size: 5,984 tokens

# rtx 3090 kvmem 0.30
# (EngineCore_DP0 pid=457674) INFO 04-14 14:56:30 [kv_cache_utils.py:1307] GPU KV cache size: 7,616 tokens


# rtx 3090 kvmem 0.95
# (EngineCore_DP0 pid=2148160) INFO 04-13 13:05:49 [kv_cache_utils.py:1307] GPU KV cache size: 151,536 tokens

# Testing with MNS=30, i.e., all reqs

# rtx 4090 kvmem 0.30
# (EngineCore_DP0 pid=1094961) INFO 04-16 14:23:13 [kv_cache_utils.py:1307] GPU KV cache size: 7,536 tokens


def print_eval(df, cols_of_interest, test_case):
    df_filt = df.copy()
    
    def smart(x):
        if abs(x) < 100:
            return f"{x:.2f}"
        return f"{x:,.0f}"
    num_cols = df_filt.select_dtypes(include="number").columns
    df_filt[num_cols] = df_filt[num_cols].map(smart)
    
    df_filt = df_filt[df_filt['test_case'] == test_case]
    df_filt = df_filt[cols_of_interest]
    df_filt = df_filt.set_index(df_filt.columns[:3].tolist())
    df_filt = df_filt.sort_values(['scheduler', 'kvmem', 'offload'])
    # print(df_filt)
        
    def show_5col_blocks(df):
        n = 5
        cols = df.columns
        
        for i in range(0, len(cols), n):
            display(df.iloc[:, i:i+n])
    
    show_5col_blocks(df_filt)


# Initial eval
cols_of_interest_initial = ['scheduler', 'kvmem', 'offload',  'throughput',
                            'total_input_tokens', 'total_output_tokens']
cols_of_interest_perf = ['scheduler', 'kvmem', 'offload',  
        'mean_ttft_ms', 'p50_ttft_ms', 'p75_ttft_ms', 'p90_ttft_ms', 'p99_ttft_ms', 
        'mean_tpot_ms', 'p50_tpot_ms', 'p75_tpot_ms', 'p90_tpot_ms', 'p99_tpot_ms',
        'mean_itl_ms', 'p50_itl_ms', 'p75_itl_ms', 'p90_itl_ms', 'p99_itl_ms',
        'mean_e2el_ms', 'p50_e2el_ms', 'p75_e2el_ms', 'p90_e2el_ms', 'p99_e2el_ms',]
        # 'throughput']

section("Throughput")
print_eval(df, cols_of_interest_initial, 'throughput')
print_eval(df, cols_of_interest_perf, 'throughput')

# display(HTML("<hr>"))

section("ShareGPT")
print_eval(df, cols_of_interest_initial, 'share')
print_eval(df, cols_of_interest_perf, 'share')

Index(['date', 'backend', 'model_id', 'tokenizer_id', 'num_prompts',
       'request_rate', 'burstiness', 'max_concurrency', 'duration',
       'completed', 'total_input_tokens', 'total_output_tokens',
       'request_throughput', 'request_goodput', 'output_throughput',
       'total_token_throughput', 'mean_ttft_ms', 'median_ttft_ms',
       'std_ttft_ms', 'p50_ttft_ms', 'p75_ttft_ms', 'p90_ttft_ms',
       'p99_ttft_ms', 'mean_tpot_ms', 'median_tpot_ms', 'std_tpot_ms',
       'p50_tpot_ms', 'p75_tpot_ms', 'p90_tpot_ms', 'p99_tpot_ms',
       'mean_itl_ms', 'median_itl_ms', 'std_itl_ms', 'p50_itl_ms',
       'p75_itl_ms', 'p90_itl_ms', 'p99_itl_ms', 'mean_e2el_ms',
       'median_e2el_ms', 'std_e2el_ms', 'p50_e2el_ms', 'p75_e2el_ms',
       'p90_e2el_ms', 'p99_e2el_ms', 'scheduler', 'offload', 'kvmem',
       'test_case'],
      dtype='object')
['throughput' 'share']

                        throughput total_input_tokens total_output_tokens
scheduler kvmem offload
FCFS      0.3   20             457                150              57,000
                4              461                150              57,000
                none           440                150              57,000
          0.95  20           1,336                150              57,000
                4            1,332                150              57,000
                none         1,339                150              57,000
RR        0.3   20             472                150              57,000
                4              358                150              57,000
                none           320                150              57,000
          0.95  20           1,324                150              57,000
                4            1,267                150              57,000
                none         1,319                150              57,000

                        mean_ttft_ms p50_ttft_ms p75_ttft_ms p90_ttft_ms  \
scheduler kvmem offload
FCFS      0.3   20             37.32       37.69       40.30       41.71
                4              37.43       36.52       41.14       43.08
                none           41.61       41.81       46.29       48.73
          0.95  20             34.97       34.88       38.95       41.93
                4              38.85       37.57       44.27       47.45
                none           30.58       31.32       33.40       34.50
RR        0.3   20             38.79       38.36       41.89       46.29
                4              39.90       40.45       43.95       46.49
                none           37.78       38.60       42.09       44.59
          0.95  20             39.12       39.97       42.10       45.06
                4              36.13       35.75       39.33       43.50
                none           40.03       39.94       42.49       44.01

                        p99_ttft_ms
scheduler kvmem offload
FCFS      0.3   20            45.23
                4             45.50
                none          52.00
          0.95  20            43.90
                4             49.92
                none          36.77
RR        0.3   20            47.83
                4             47.62
                none          45.64
          0.95  20            47.18
                4             47.74
                none          45.02

                        mean_tpot_ms p50_tpot_ms p75_tpot_ms p90_tpot_ms  \
scheduler kvmem offload
FCFS      0.3   20             40.10       37.43       56.06       62.41
                4              40.11       38.14       52.65       63.65
                none           43.20       43.57       56.99       61.91
          0.95  20             22.48       22.48       22.48       22.48
                4              22.53       22.53       22.53       22.54
                none           22.44       22.44       22.44       22.44
RR        0.3   20             60.13       60.18       61.84       62.95
                4              78.71       79.41       82.02       83.18
                none           85.00       85.12       89.27       92.18
          0.95  20             22.61       22.62       22.62       22.62
                4              23.71       23.71       23.71       23.71
                none           22.74       22.74       22.75       22.75

                        p99_tpot_ms
scheduler kvmem offload
FCFS      0.3   20            65.60
                4             65.20
                none          67.92
          0.95  20            22.48
                4             22.54
                none          22.44
RR        0.3   20            63.53
                4             83.81
                none          93.54
          0.95  20            22.62
                4             23.71
                none          22.75

                        mean_itl_ms p50_itl_ms p75_itl_ms p90_itl_ms  \
scheduler kvmem offload
FCFS      0.3   20            40.10      18.10      19.11      19.60
                4             40.11      18.07      19.14      19.48
                none          43.20      18.59      19.17      19.43
          0.95  20            22.48      22.48      24.45      25.48
                4             22.53      21.72      23.99      26.44
                none          22.44      22.43      24.39      25.43
RR        0.3   20            60.14      18.49      19.28      19.56
                4             78.71      18.77      19.30      19.54
                none          85.00      19.09      19.49      19.81
          0.95  20            22.61      22.59      24.65      25.74
                4             23.71      22.70      26.20      29.19
                none          22.74      22.62      24.65      25.66

                        p99_itl_ms
scheduler kvmem offload
FCFS      0.3   20           20.12
                4            19.91
                none         19.98
          0.95  20           26.35
                4            31.94
                none         26.32
RR        0.3   20           21.31
                4            27.93
                none           133
          0.95  20           26.50
                4            36.83
                none         26.81

                        mean_e2el_ms p50_e2el_ms p75_e2el_ms p90_e2el_ms  \
scheduler kvmem offload
FCFS      0.3   20            76,179      71,111     106,504     118,552
                4             76,212      72,455     100,019     120,905
                none          82,085      82,771     108,280     117,624
          0.95  20            42,715      42,717      42,722      42,724
                4             42,829      42,830      42,833      42,840
                none          42,636      42,637      42,640      42,641
RR        0.3   20           114,226     114,331     117,466     119,577
                4            149,519     150,844     155,797     158,000
                none         161,452     161,677     169,571     175,085
          0.95  20            42,983      42,985      42,988      42,991
                4             45,054      45,054      45,060      45,063
                none          43,229      43,231      43,235      43,237

                        p99_e2el_ms
scheduler kvmem offload
FCFS      0.3   20          124,610
                4           123,851
                none        129,033
          0.95  20           42,726
                4            42,843
                none         42,643
RR        0.3   20          120,679
                4           159,192
                none        177,669
          0.95  20           42,993
                4            45,067
                none         43,238

                        throughput total_input_tokens total_output_tokens
scheduler kvmem offload
FCFS      0.3   20             888              6,523               6,390
                4            1,011              6,523               6,390
                none         1,018              6,523               6,390
          0.95  20             889              6,523               6,390
                4            1,007              6,523               6,390
                none           889              6,523               6,390
RR        0.3   20             953              6,523               6,390
                4              954              6,523               6,390
                none           889              6,523               6,390
          0.95  20             953              6,523               6,390
                4              889              6,523               6,390
                none           889              6,523               6,390

                        mean_ttft_ms p50_ttft_ms p75_ttft_ms p90_ttft_ms  \
scheduler kvmem offload
FCFS      0.3   20               328         368         531         542
                4                313         308         470         568
                none             318         292         454         553
          0.95  20               314         359         520         532
                4                319         360         523         542
                none             326         367         528         548
RR        0.3   20               309         352         515         540
                4                340         385         547         573
                none             337         363         522         550
          0.95  20               311         302         387         543
                4                310         284         523         534
                none             338         365         524         552

                        p99_ttft_ms
scheduler kvmem offload
FCFS      0.3   20              564
                4               571
                none            555
          0.95  20              553
                4               547
                none            552
RR        0.3   20              545
                4               577
                none            555
          0.95  20              546
                4               557
                none            556

                        mean_tpot_ms p50_tpot_ms p75_tpot_ms p90_tpot_ms  \
scheduler kvmem offload
FCFS      0.3   20             25.62       19.99       23.87       30.81
                4              26.40       20.19       22.65       30.92
                none           26.37       19.99       22.75       31.23
          0.95  20             25.62       20.00       23.78       30.80
                4              25.14       19.84       23.73       30.39
                none           25.42       19.95       23.82       30.41
RR        0.3   20             25.43       19.95       23.74       30.67
                4              25.88       20.10       23.98       30.72
                none           25.42       19.96       23.77       28.61
          0.95  20             25.06       20.04       23.64       29.74
                4              25.59       20.12       23.74       30.79
                none           25.42       19.96       23.77       28.63

                        p99_tpot_ms
scheduler kvmem offload
FCFS      0.3   20            83.30
                4             96.00
                none          97.16
          0.95  20            83.27
                4             81.42
                none          81.68
RR        0.3   20            82.66
                4             86.25
                none          83.21
          0.95  20            78.83
                4             83.18
                none          83.29

                        mean_itl_ms p50_itl_ms p75_itl_ms p90_itl_ms  \
scheduler kvmem offload
FCFS      0.3   20            20.00      19.11      19.36      19.58
                4             19.42      19.14      19.45      19.65
                none          19.27      19.06      19.43      19.64
          0.95  20            20.02      19.11      19.40      19.63
                4             19.19      19.03      19.34      19.59
                none          19.97      19.11      19.41      19.64
RR        0.3   20            19.67      19.05      19.42      19.62
                4             19.66      19.04      19.43      19.67
                none          19.91      19.02      19.43      19.79
          0.95  20            19.69      19.11      19.42      19.63
                4             20.00      19.02      19.37      19.62
                none          19.91      19.06      19.41      19.68

                        p99_itl_ms
scheduler kvmem offload
FCFS      0.3   20           19.99
                4            20.09
                none         20.12
          0.95  20           20.21
                4            20.08
                none         20.05
RR        0.3   20           20.00
                4            20.12
                none         20.40
          0.95  20           20.15
                4            20.00
                none         20.04

                        mean_e2el_ms p50_e2el_ms p75_e2el_ms p90_e2el_ms  \
scheduler kvmem offload
FCFS      0.3   20             4,568       3,234       6,736       9,337
                4              4,429       3,244       6,747       9,259
                none           4,403       3,231       6,729       9,226
          0.95  20             4,558       3,224       6,729       9,331
                4              4,387       3,215       6,695       9,169
                none           4,559       3,226       6,726       9,326
RR        0.3   20             4,479       3,221       6,699       9,286
                4              4,507       3,257       6,734       9,320
                none           4,558       3,234       6,714       9,319
          0.95  20             4,486       3,217       6,715       9,281
                4              4,549       3,219       6,705       9,309
                none           4,559       3,235       6,713       9,317

                        p99_e2el_ms
scheduler kvmem offload
FCFS      0.3   20           14,436
                4            12,654
                none         12,539
          0.95  20           14,418
                4            12,564
                none         14,428
RR        0.3   20           13,447
                4            13,441
                none         14,423
          0.95  20           13,449
                4            14,397
                none         14,425